# Blocked words can not contain capitals. The following format must be followed
#  Word,Reason eg'penguin, he have flipper'
Blocked words:
  - noot, I dont like this
  - bob, Its tasty
  - john,You can guess
url: Noot.xyz
Database:
  IP: localhost
  Port: 0000
  Username: root
  Password: root
  Enabled: false
