name: Chat-Filter
version: 8.3
main: kineticnetwork.net.chatfilter.ChatFilter
api-version: 1.16
authors: [killbot24]
description: Chat filter
commands:
 Chatfilter:
    description: Base command of chat filter
    usage: /chatfilter
    permission: Chatfilter.use

 filter:
   description: only use is to tell ppl hey wrong command
   usage: /filter
   permission: Chatfilter.use
